# Generated by Django 5.2.7 on 2025-10-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('category', models.CharField(choices=[('FACE', 'Twarz'), ('BODY', 'Ciało'), ('HAIR', 'Włosy'), ('MAKEUP', 'Makijaż'), ('HANDS', 'Dłonie')], max_length=100, verbose_name='Kategoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.ManyToManyField(related_name='cosmetics', to='ingredients.ingredient', verbose_name='Składniki')),
            ],
            options={
                'verbose_name': 'Kosmetyk',
                'verbose_name_plural': 'Kosmetyki',
            },
        ),
    ]
