# Generated by Django 6.0b1 on 2025-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0001_initial'),
        ('ingredients', '0004_alter_ingredient_options_alter_ingredient_inci_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmetic',
            name='category',
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='main_category',
            field=models.CharField(choices=[('FACE', 'Face'), ('MAKEUP', 'Make-up'), ('BODY', 'Body'), ('HANDS', 'Hands')], default='FACE', max_length=20, verbose_name='Main Category (Face, Make-up, Body, Hands)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='product_type',
            field=models.CharField(blank=True, help_text='Specific product type (only for Make-up)', max_length=50, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Face: Cleanser, Toner, Serum, Moisturizer or SPF, Makeup: Eyes, Face or Lips', max_length=50, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='ingredients',
            field=models.ManyToManyField(related_name='cosmetics', to='ingredients.ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
