# Generated by Django 6.0b1 on 2025-12-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_remove_cosmetic_category_cosmetic_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='main_category',
            field=models.CharField(choices=[('FACE', 'Face'), ('MAKEUP', 'Make-up'), ('BODY', 'Body')], max_length=20, verbose_name='Main Category (Face, Make-up, Body)'),
        ),
    ]
