# Generated by Django 6.0b1 on 2026-01-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_alter_cosmetic_main_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosmetic',
            options={'verbose_name': 'Cosmetic', 'verbose_name_plural': 'Cosmetics'},
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='ingredients_text',
            field=models.TextField(blank=True, help_text='Paste full INCI list (separated by commas).', verbose_name='Paste ingredients list'),
        ),
    ]
