# Generated by Django 6.0b1 on 2026-01-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0004_alter_cosmetic_options_cosmetic_ingredients_text'),
        ('ingredients', '0004_alter_ingredient_options_alter_ingredient_inci_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='cosmetics', to='ingredients.ingredient', verbose_name='Ingredients'),
        ),
    ]
