# Generated by Django 6.0.7 on 2026-08-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0005_alter_cosmetic_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosmetic',
            options={'ordering': ['id'], 'verbose_name': 'Cosmetic', 'verbose_name_plural': 'Cosmetics'},
        ),
    ]
