# Generated by Django 6.0b1 on 2025-12-06 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0004_alter_ingredient_options_alter_ingredient_inci_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(blank=True, choices=[('DRY', 'Dry'), ('OILY', 'Oily'), ('COMBINATION', 'Combination'), ('SENSITIVE', 'Sensitive'), ('NORMAL', 'Normal')], max_length=20, verbose_name='Skin type')),
                ('skin_concerns', models.TextField(blank=True, help_text='Acne, wrinkles, dark spots, redness...', verbose_name='Skin concerns')),
                ('vegan_only', models.BooleanField(default=False, verbose_name='Vegan products only')),
                ('cruelty_free_only', models.BooleanField(default=False, verbose_name='Cruelty-free products only')),
                ('fragrance_free', models.BooleanField(default=False, verbose_name='Fragrance-free products preferred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergic_to', models.ManyToManyField(blank=True, related_name='allergic_users', to='ingredients.ingredient', verbose_name='Allergic to ingredients')),
                ('avoided_ingredients', models.ManyToManyField(blank=True, related_name='avoided_by_users', to='ingredients.ingredient', verbose_name='Avoided ingredients (not allergic, but prefer to avoid)')),
                ('preferred_ingredients', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='ingredients.ingredient', verbose_name='Preferred ingredients')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
