# Generated by Django 6.0b1 on 2026-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_options_alter_ingredient_inci_name_and_more'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allergic_to',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avoided_ingredients',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cruelty_free_only',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fragrance_free',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_ingredients',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skin_concerns',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skin_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vegan_only',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='moderate_ingredients',
            field=models.ManyToManyField(blank=True, related_name='moderate_for_users', to='ingredients.ingredient', verbose_name='Moderate ingredients (YELLOW)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='safe_ingredients',
            field=models.ManyToManyField(blank=True, related_name='safe_for_users', to='ingredients.ingredient', verbose_name='Safe ingredients (GREEN)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unsafe_ingredients',
            field=models.ManyToManyField(blank=True, related_name='unsafe_for_users', to='ingredients.ingredient', verbose_name='Unsafe ingredients (RED)'),
        ),
    ]
