# Generated by Django 6.0b1 on 2026-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0005_alter_cosmetic_ingredients'),
        ('preferences', '0002_remove_userprofile_allergic_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_cosmetics',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='cosmetics.cosmetic', verbose_name='Favorite Cosmetics'),
        ),
    ]
