# Generated by Django 6.0b1 on 2025-11-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_allergen',
            field=models.BooleanField(default=False, verbose_name='Alergen'),
        ),
    ]
