# Generated by Django 6.0b1 on 2025-11-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_is_allergen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='is_allergen',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zastosowanie'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='inci_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa INCI'),
        ),
    ]
