# Generated by Django 6.0b1 on 2025-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_remove_ingredient_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='inci_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='INCI Name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, verbose_name='Purpose'),
        ),
    ]
