# Generated by Django 6.0.7 on 2026-08-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_options_alter_ingredient_inci_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
    ]
